# Euler Problem 2
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

class	Fibo
	def initialize
		@sum = 4_000_000
		@arr_of_fibs = [1,2]
	end

	def start_fibs
		loop do
			break if @arr_of_fibs.last > @sum
			x = @arr_of_fibs.last(2).inject(:+)
			@arr_of_fibs << x
		end
		@arr_of_fibs
	end

	def sum_evens
		@arr_of_fibs.select{|d| d.even? }.inject(:+)
	end
end

# completed 5/16/2015